export default {
  SET_USER_STATE: "SET_USER_STATE",
  SET_PRODUCT_STATE: "SET_PRODUCT_STATE",
  ADD_PRODUCT_STATE: "ADD_PRODUCT_STATE",
  DELETE_PRODUCT_STATE: "DELETE_PRODUCT_STATE",
  UPDATE_PRODUCT_STATE: "UPDATE_PRODUCT_STATE"
};
